---
DB_HOST_PRIVATE_IP: 172.31.73.75
DB_NAME: alejandroalsa
DB_USER: alejandroalsa
DB_PASS: alejandroalsa

php_paquetes:
  - php
  - libapache2-mod-php 
  - php-mysql

WP_HOME: https://alejandrosanchez.ddns.net
WP_SITEURL: https://alejandrosanchez.ddns.net/wordpress

EMAIL: alejandro@alejandroalsa.es
DOMAIN: alejandrosanchez.ddns.net

NFS_SERVER_IP_PRIVATE: 172.31.69.73

IP_HTTP_SERVER_1: 3.227.235.212
IP_HTTP_SERVER_2: 3.237.46.163
