---
- name: Playbook para instalar la pila backend
  hosts: bak
  become: true

  tasks:

    - name: Variables de Configuracion
      ansible.builtin.include_vars:
        ../../variables/variables.yml

    - name: Instalando el gestor de paquetes de Python3
      apt:
        name: python3-pip
        state: present

    - name: Instalamos el modulo de pymysql
      ansible.builtin.pip:
        name: pymysql
        state: present

    - name: Crear una base de datos
      community.mysql.mysql_db:
        name: "{{ DB_NAME }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Creamos un usuario para la Base de datos
      no_log: true
      community.mysql.mysql_user:
        name: "{{ DB_USER }}"
        host: '%'
        password: "{{ DB_PASS }}"
        priv: "{{ DB_NAME }}.*:ALL,GRANT"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Reiniciamos el servidor mysql
      ansible.builtin.service:
        name: mysql
        state: restarted
