---
- name: Playbook despliege de Wordpress
  hosts: SERVER
  become: true

  tasks:

  - name: Variables de Configuracion
    ansible.builtin.include_vars:
      variables.yml

  - name: Eliminando el ZIP latest.zip de /tmp/latest.zip
    file:
      path: /tmp/latest.zip
      state: absent

  - name: Eliminando el directorio de Wordpress de /var/www/html/
    file:
      path: /var/www/html/wordpress
      state: absent

  - name: Eliminando el archivo index.html de /var/www/html/index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Descargando UNZIP
    apt:
      name: unzip
      state: present

  - name: Descargando Wordpress
    ansible.builtin.get_url:
      url: https://wordpress.org/latest.zip
      dest: /var/www/html/

  - name: Eliminando el archivo index de /var/www/html/
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Descomprimiendo Wordpress + añadiendo usuario www-data y grupo www-data
    ansible.builtin.unarchive:
      src: /var/www/html/wordpress-6.1.1.zip
      dest: /var/www/html/
      remote_src: true
      owner: www-data
      group: www-data

  - name: Eliminando el archivo wordpress-6.1.1.zip de /var/www/html/
    file:
      path: /var/www/html/wordpress-6.1.1.zip
      state: absent

  - name: Instalando el gestor de paquetes de Python3
    apt:
      name: python3-pip
      state: present

  - name: Instalando el modulo de pymysql
    pip:
      name: pymysql
      state: present

  - name: Creando Base de Datos de Wordpress
    community.mysql.mysql_db:
      name: "{{ DB_NAME }}"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Creando usuario para la Base de Datos
    no_log: true
    mysql_user:
      name: "{{ DB_USER }}"
      host: '%'
      password: "{{ DB_PASS }}"
      priv: "{{ DB_NAME }}.*:ALL,GRANT"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Reiniciando el Servicio de MySQL
    service:
      name: mysql
      state: restarted

  - name: Copiando el archivo de configuración de ejemplo y creando uno nuevo
    copy:
      remote_src: true
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php

  - name: Configurando las variables de conexion (DB_NAME)
    ansible.builtin.replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: database_name_here
      replace: "{{ DB_NAME }}"

  - name: Configurando las variables de conexion (DB_USER)
    ansible.builtin.replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: username_here
      replace: "{{ DB_USER }}"

  - name: Configurando las variables de conexion (DB_PASS)
    ansible.builtin.replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: password_here
      replace: "{{ DB_PASS }}"

  - name: Configurando las variables de conexion (DB_HOST)
    ansible.builtin.replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: password_here
      replace: "{{ DB_HOST }}"

  - name: Añadiendo WP_HOME Y WP_SITEURL a wp-config.php
    ansible.builtin.blockinfile:
      path: /var/www/html/wordpress/wp-config.php
      insertafter: DB_COLLATE
      block: |
            define('WP_HOME', "{{ WP_HOME }}");
            define('WP_SITEURL', "{{ WP_SITEURL }}");

  - name: Copiando index.php de /var/www/html/wordpress/ a /var/www/html/
    copy:
      remote_src: true
      src: /var/www/html/wordpress/index.php
      dest: /var/www/html/index.php

  - name: Configurando las variables (wp-blog-header)
    ansible.builtin.replace:
      path: /var/www/html/index.php
      regexp: wp-blog-header.php
      replace: wordpress/wp-blog-header.php

  - name: Anadiendo usuario www-data y grupo www-data a todos los directorio y archivos de /var/www/html
    ansible.builtin.file:
      path: /var/www/html
      owner: www-data
      group: www-data
      recurse: true

  - name: Reiniciando el servidor Web Apache2.4
    service:
      name: apache2
      state: restarted
