---
- name: Playbook para instalar la pila LAMP
  hosts: SERVER
  become: true

  tasks:

    - name: Actualizando repositorios
      apt:
        update_cache: true

    - name: Instalando servidor web Apache2.4
      apt:
        name: apache2
        state: present

    - name: Instalando PHP y mudulos de PHP
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Instalando sistema de base de datos MySQL
      apt:
        name: mysql-server
        state: present

    - name: Reiniciando Apache2.4
      service:
        name: apache2.service
        state: restarted
