AWSTemplateFormatVersion: '2010-09-09'
Description: Grupo de seguridad para LoadBalancer
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sg-loadbalancer
      GroupDescription: Grupo de seguridad para LoadBalancer
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

