---
- name: PlayBook para instalar Certbot
  hosts: balanceador
  become: true

  tasks:

    - name: Añadimos las variables
      ansible.builtin.include_vars:
        ../../variables/variables.yml

    - name: Asegurando de que Snapd esté instalado
      ansible.builtin.package:
        name: snapd
        state: present
      register: snapd_install

    - name: Asegurando de que snapd esté habilitado.
      ansible.builtin.systemd:
        name: snapd.socket
        enabled: true
        state: started

    - name: Instalando y actualizando snapd
      ansible.builtin.shell: snap install core; snap refresh core
      changed_when: true
      failed_when: false
      when: snapd_install is changed

    - name: Instalando Certbot
      community.general.snap:
        name: certbot
        classic: true

    - name: Creando un alias para Certbot
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link

    - name: Obteniendo certificado SSL y configurando el servidor web.
      ansible.builtin.command: certbot --apache -m {{ EMAIL }} --agree-tos --no-eff-email -d {{ DOMAIN }}

    - name: Reinicamos apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
