---
- name: Playbook despliege de Wordpress
  hosts: BACKEND
  become: true

  tasks:

  - name: Variables de Configuracion
    ansible.builtin.include_vars:
      variables.yml

  - name: Instalando el gestor de paquetes de Python3
    apt:
      name: python3-pip
      state: present

  - name: Instalando el modulo de pymysql
    pip:
      name: pymysql
      state: present

  - name: Creando Base de Datos de Wordpress
    community.mysql.mysql_db:
      name: "{{ DB_NAME }}"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Creando usuario para la Base de Datos
    no_log: true
    mysql_user:
      name: "{{ DB_USER }}"
      host: '%'
      password: "{{ DB_PASS }}"
      priv: "{{ DB_NAME }}.*:ALL,GRANT"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Reiniciando el Servicio de MySQL
    service:
      name: mysql
      state: restarted

  - name: Reiniciando el servidor Web Apache2.4
    service:
      name: apache2
      state: restarted
