---
- name: Playbook para crear un grupo de seguridad y una instancia EC2 en AWS para FRONTEND
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ec2_security_group: frontend_ec2
    ec2_security_group_description: Grupo de frontend para EC2
    ec2_instance_name: frontend_01
    ec2_image: ami-06878d265978313ca
    ec2_instance_type: t2.small
    ec2_key_name: vockey

  tasks:
  - name: Crear un grupo de seguridad
    ec2_group:
      name: "{{ ec2_security_group }}"
      description: "{{ ec2_security_group_description }}"
      rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    register: security_group

  - name: Crear una instancia EC2
    ec2_instance:
      name: "{{ ec2_instance_name }}"
      key_name: "{{ ec2_key_name }}"
      security_group: "{{ ec2_security_group }}"
      instance_type: "{{ ec2_instance_type }}"
      image_id: "{{ ec2_image }}"
      state: running
    register: ec2
