---
- name: Playbook para instalar  wordpress
  hosts: front
  become: true

  tasks:

  - name: Añadimos las variables
    ansible.builtin.include_vars:
      ../../variables/variables.yml

  - name: Actualizar los repositorios
    ansible.builtin.apt:
      update_cache: true

  - name: Instalamos el cliente nfs
    ansible.builtin.apt:
      name: nfs-common
      state: present

  - name: Montamos el directorio compartido
    ansible.posix.mount:
      path: /var/www/html
      src: "{{ NFS_SERVER_IP_PRIVATE }}:/var/www/html"
      state: mounted
      fstype: nfs
      opts: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800
