---
- name: Playbook para crear balanceador de carga en Apache2.4
  hosts: balanceador
  become: true

  tasks:

    - name: Variables de Configuracion
      ansible.builtin.include_vars:
        ../../variables/variables.yml

    - name: Instalando servidor web Apache2.4
      apt:
        name: apache2
        state: present

    - name: Activando modulos de Apache
      community.general.apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - proxy
        - proxy_http
        - proxy_ajp
        - rewrite
        - deflate
        - headers
        - proxy_balancer
        - proxy_connect
        - proxy_html
        - lbmethod_byrequests

    - name: Eliminando 000-default.conf
      ansible.builtin.file:
        path: /etc/apache2/sites-available/000-default.conf
        state: absent

    - name: Añadimos dir.conf
      ansible.builtin.template:
        src: ../../templates/000-default_balanceador.j2
        dest: /etc/apache2/sites-available/000-default.conf
        mode: 0644

    - name: Reiniciando Apache2.4
      ansible.builtin.service:
        name: apache2.service
        state: restarted
