---
- name: Playbook para instalar DOCKER
  hosts: EC2
  become: true

  tasks:

    - name: Variables de Configuracion
      ansible.builtin.include_vars:
        ../variables/variables.yml

    - name: Actualizando repositorios
      ansible.builtin.apt:
        update_cache: true

    - name: Instalando Docker
      ansible.builtin.apt:
        name: "{{ Docker.Package }}"
        state: present

    - name: Creando un directorio para Docker Compose
      ansible.builtin.file:
        path: "{{ Type_Install.User_Home }}"
        mode: 0775
        owner: "{{ User.Name_Group }}"
        group: "{{ User.Name_Group }}"
        state: directory

    - name: Descargando Docker Compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64
        dest: "{{ Type_Install.User_Home }}/{{ Compose_File.New_Name }}"
        mode: 0775
        owner: "{{ User.Name_Group }}"
        group: "{{ User.Name_Group }}"

    - name: Asignando e grupo Docker al usuario
      ansible.builtin.user:
        name: "{{ User.Name_Group }}"
        groups: "{{ Docker.Group }}"
        append: true

    - name: Instalando el gestor de paquetes de Python
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Instalando Docker para Python
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Instalando Docker Compose para Python
      ansible.builtin.pip:
        name: docker-compose
        state: present

    - name: Copiando los archivos del Docker Compose al HOST
      ansible.builtin.copy:
        src: "{{ Compose_File.Local_Files }}"
        dest: "{{ User.Directory }}"
        owner: ubuntu
        group: ubuntu
        mode: 0644

    - name: Reiniciando Docker
      ansible.builtin.service:
        name: docker
        state: restarted
