---
- name: Playbook para instalar la pila LAMP
  hosts: SERVER
  become: true

  tasks:

    - name: Actualizando repositorios
      apt:
        update_cache: true

    - name: Instalando servidor web Apache2.4
      apt:
        name: apache2
        state: present

    - name: Reiniciando Apache2.4
      service: 
        name: apache2.service
        state: restarted
